# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='group',
            new_name='Category',
        ),
    ]
